services:
  prod:
    image: iwinter78/microblog:${VERSION-prod:-1.0.0-prod}
    build:
      context: .
      dockerfile: docker/Dockerfile_prod
    environment:
      - DATABASE_URL=mysql+pymysql://microblog:microblog@13.74.42.62:3306/microblog
      - APP_VERSION=${VERSION:-1.0.0-prod}
    ports:
      - "8000:5000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s

volumes:
  db_data: