---
-   name: Get facts by tags
    azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group }}"
    delegate_to: localhost
    register: az_facts



-   name: Display all variables/facts known for a host
    debug:
        var: az_facts



-   name: add instance to hosts
    add_host:
        name: "{{ item.tags.PublicIP }}"
        groups:
        - "{{ item.name[0:-3] }}" # instance name from provision_instances/vars/main.yml
        - "{{ item.tags.Type }}" # instance type from provision_instances/vars/main.yml
        - devops
        # the keys below are dynamic and can have any name and value. A way to add data to the host which can be read later
        iname: "{{ item.name[0:-3] }}"
        itype: "{{ item.tags.Type }}"
    with_items: "{{ az_facts.vms }}"
    when: item.tags.PublicIP is defined and item.power_state == "running"

-   name: Get facts by tags
    azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group }}"
        tags:
            - "StudentId:{{ vmtags.StudentId }}"
    register: az_facts

-   name: Build hosts file content
    set_fact:
        hosts_content: |
            [local]
            localhost ansible_connection=local

            [provision_targets]
            appserver1
            appserver2
            database
            loadbalancer

            [app_servers]
            {% for vm in az_facts.vms | selectattr('tags.Type', 'equalto', 'appserver') %}
            appserver{{ loop.index }}.{{ domain_name }} ansible_host={{ vm.tags.PublicIP }} ansible_user=azureuser
            {% endfor %}

            [db_servers]
            {% for vm in az_facts.vms | selectattr('tags.Type', 'equalto', 'database') %}
            db.{{ domain_name }} ansible_host={{ vm.tags.PublicIP }} ansible_user=azureuser
            {% endfor %}

            [load_balancers]
            {% for vm in az_facts.vms | selectattr('tags.Type', 'equalto', 'loadbalancer') %}
            lb.{{ domain_name }} ansible_host={{ vm.tags.PublicIP }} ansible_user=azureuser
            {% endfor %}

            [devops:children]
            app_servers
            db_servers
            load_balancers

            [webservers:children]
            app_servers

            [databases:children]
            db_servers

-   name: Write hosts file
    copy:
        content: "{{ hosts_content }}"
        dest: "{{ playbook_dir }}/hosts"
        backup: yes
    delegate_to: localhost



-   name: Display all variables/facts known for a host
    debug:
        var: hostvars