---
- name: update apt cache
  become: true
  apt:
    update_cache: true

- name: install ca-certificates and curl
  become: true
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: create Docker GPG keyring directory
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: add Docker GPG key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

- name: set Docker GPG key permissions
  become: true
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: 'a+r'

- name: add Docker repository
  become: true
  shell: |
    tee /etc/apt/sources.list.d/docker.sources <<EOF
    Types: deb
    URIs: https://download.docker.com/linux/ubuntu
    Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    Components: stable
    Signed-By: /etc/apt/keyrings/docker.asc
    EOF

- name: update apt cache again
  become: true
  apt:
    update_cache: true

- name: install docker
  become: true
  apt:
    name: docker-ce
    state: present

- name: install docker-compose plugin
  become: true
  apt:
    name: docker-compose-plugin
    state: present

- name: start and enable docker service
  become: true
  systemd:
    name: docker
    state: started
    enabled: true

- name: add deploy user to docker group
  become: true
  user:
    name: deploy
    groups: docker
    append: true

- name: usermod docker group
  become: true
  command: usermod -aG docker $USER

- name: newgrp docker
  become: true
  command: newgrp docker

- name: create microblog directory
  become: true
  file:
    path: /home/deploy/microblog
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'

- name: copy docker-compose file
  become: true
  copy:
    src: ../../../../docker-compose.prod.yml
    dest: /home/deploy/microblog/docker-compose.yml
    owner: deploy
    group: deploy
    mode: '0644'

- name: pull down latest docker images
  command: docker pull iwinter78/microblog:{{ version | default('1.0.0-prod') }}
  args:
    chdir: /home/deploy/microblog

- name: initialize docker swarm
  command: docker swarm init
  args:
    chdir: /home/deploy/microblog
  ignore_errors: true
  when: inventory_hostname == 'appserver1.snabbnudlar.dev'

- name: get swarm join token
  command: docker swarm join-token -q worker
  register: swarm_join_token
  args:
    chdir: /home/deploy/microblog
  when: inventory_hostname == 'appserver1.snabbnudlar.dev'

- name: deploy/update stack
  command: docker stack deploy -c docker-compose.yml microblog
  args:
    chdir: /home/deploy/microblog
  when: inventory_hostname == 'appserver1.snabbnudlar.dev'

- name: make appserver2 join the swarm
  command: docker swarm join --token {{ hostvars['appserver1.snabbnudlar.dev'].swarm_join_token.stdout }} {{ hostvars['appserver1.snabbnudlar.dev'].ansible_host }}:2377
  when: inventory_hostname == 'appserver2.snabbnudlar.dev'
  ignore_errors: true