---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-FILI22-DV1673-H25-LP2 # Change me
domain_name: kaosfabriken.dev # Change me

admin_email: fili22@student.bth.se

vmtags:
    StudentId: fili22 # Change me


pub_ssh_key_locations:
    - "{{ playbook_dir }}/roles/keys/azure.pub"
    - "{{ playbook_dir }}/roles/keys/kaos.pub"

pub_ssh_key_location: "{{ lookup('env', 'HOME') }}/.ssh/kaos.pub"


server_user: "deploy"
server_user_pass: "123123" # change me
server_user_groups:
    -   sudo
