---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-SEOL23-DV1673-H25-LP2 # Change me
domain_name: snabbnudlar.dev # Change me

admin_email: seol23@student.bth.se

vmtags:
    StudentId: seol23 # Change me


pub_ssh_key_location: '/home/sebbe/.ssh/azure.pub' # Change me, your local ssh key!


server_user: "deploy"
server_user_pass: "123123" # change me
server_user_groups:
    -   sudo
