apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microblog
  template:
    metadata:
      labels:
        app: microblog
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z mysql 3306; do
              echo "Waiting for MySQL..."
              sleep 2
            done
      containers:
      - name: microblog
        image: iwinter78/microblog:master-prod
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: mysql+pymysql://microblog:microblog@mysql:3306/microblog
        ports:
        - containerPort: 5000
        securityContext:
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: microblog
spec:
  type: LoadBalancer
  selector:
    app: microblog
  ports:
    - port: 80
      targetPort: 5000
