# Gather facts from remote instance and set as hosts
---
-   hosts: local
    connection: local
    gather_facts: False
    collections:
        - azure.azcollection
    roles:
        - gather_instances

-   name: Debug hostvars
    hosts: local
    gather_facts: False
    tasks:
        - name: Display all hostvars for localhost
          debug:
            var: hostvars['localhost']
        
        - name: Display all groups
          debug:
            var: groups
