---
-   name: Set root password
    user:
        name: root
        password: "{{ root_password }}"

-   name: Update apt-cache and upgrade
    apt:
        force_apt_get: yes
        update_cache: "True"
        cache_valid_time: 3600
        upgrade: yes

-   name: Install packages
    apt:
        force_apt_get: yes
        name: "{{ packages }}"

-   name: Copy unattended upgrades 10 settings
    copy:
        mode: "644"
        src: files/apt_periodic
        dest: /etc/apt/apt.conf.d/10periodic

-   name: Copy unattended upgrades 50 settings
    copy:
        mode: "644"
        src: files/apt_periodic_50
        dest: /etc/apt/apt.conf.d/50unattended-upgrades

-   name: Create user
    user:
        name: "{{ server_user }}"
        password: "{{ server_user_pass }}"
        state: present
        shell: /bin/bash
        groups: "{{ server_user_groups }}"

-   name: Add ssh-key for new user
    authorized_key:
        user: "{{ server_user }}"
        state: present
        key: "{{ lookup('file', item) }}"
    with_items: "{{ pub_ssh_key_locations }}"


-   name: Add user to sudoers
    lineinfile:
        dest: /etc/sudoers
        regexp: "{{ server_user }} ALL"
        line: "{{ server_user }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: '/usr/sbin/visudo -cf %s' # kan f√• fel med line "{{ server_user }} testing"

- name: Configure SSH security settings
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  with_items:
    - regexp: "^#?HostKey /etc/ssh/ssh_host_ed25519_key"
      line: "HostKey /etc/ssh/ssh_host_ed25519_key"
    - regexp: "^#?HostKey /etc/ssh/ssh_host_rsa_key"
      line: "HostKey /etc/ssh/ssh_host_rsa_key"
    - regexp: "^#?HostKey /etc/ssh/ssh_host_ecdsa_key"
      line: "HostKey /etc/ssh/ssh_host_ecdsa_key"
    - regexp: "^#?KexAlgorithms"
      line: "KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
    - regexp: "^#?Ciphers"
      line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    - regexp: "^#?MACs"
      line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
    - regexp: "^#?AuthenticationMethods"
      line: "AuthenticationMethods publickey"
    - regexp: "^#?LogLevel"
      line: "LogLevel VERBOSE"
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?AllowUsers"
      line: "AllowUsers {{ server_user }}"
  notify: restart ssh

-   name: Remove default user
    remote_user: "{{ server_user }}"
    user:
        name: azureuser
        state: absent
        force: yes
        remove: yes
