name: Deploy microblog

on:
  workflow_run:
    workflows: ["security-check"]
    types:
      - completed
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest git tag
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.0-prod")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Deploying version: ${VERSION}"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Force install azure collection
        run: |
          ansible-galaxy collection install azure.azcollection --force
      
      - name: Install other missing dependencies
        run: |
          pip install --upgrade msal msal-extensions azure-cli-core azure-common

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/deploy.txt
          pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt
          cd ansible && ansible-galaxy install -r requirements.yml

      - name: Setup SSH 
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/id_rsa
          echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa

      - name: Run playbook
        run: cd ansible/ && ansible-playbook -i hosts gather_instances.yml redeploy.yml --private-key=/home/runner/.ssh/id_rsa -e "version=${{ steps.version.outputs.version }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      - name: check version deployed
        run: cd ansible/ && ansible-playbook -i hosts check_version.yml --private-key=/home/runner/.ssh/id_rsa
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"